"""Full-grid VIF pilot: 100 LDCT-IQAC references x the COMPLETE Ohashi
degradation grid (12 noise + 12 blur + 144 noise+blur = 168 conditions each),
before any commitment to the full 1,000-reference / 169,000-image dataset.

Extends scripts/quality/vif_pilot.py (30 refs, reduced 3x3 combined subset)
by exercising the full 12x12 combined factorial this time -- the one part
of the grid the smaller pilot deliberately did not cover.

Does NOT generate the 169,000-image dataset, does NOT write to
data/manifests/quality_iqa_manifest.*, does NOT modify
data/raw/ldctiqa/ground_truth_score.json, and does NOT train anything.
Does NOT modify src/ct_iqa/vif/wavelet.py. All generated pixels/plots are
written under data/interim/vif_full_grid_pilot/ (gitignored via
`data/interim/**`) -- nothing generated by this script is committed.

Same PILOT-ONLY provisional parameters as the smaller pilot
(combination_order, sigma_scale) -- see module docstring below for why,
and docs/research_decisions.md items U-D01/U-D02 for the still-open
status these do not resolve.

Performance note: `vif_wavelet(profile="project")` and
`vif_wavelet_diagnostics(..., profile="project")` both build the same
steerable pyramids from scratch; calling both separately (as the smaller
pilot did) doubles the work for no benefit when diagnostics are wanted
anyway. Since the "project" profile aggregates via a plain sum
(VIFProfile.aggregation == "sum"), the final VIF score can be derived
directly from vif_wavelet_diagnostics()'s per-subband numerator/denominator
totals -- confirmed identical to calling vif_wavelet() directly (see
docs/vif_full_grid_pilot_report.md, Runtime section) -- so this script
calls diagnostics only, roughly halving per-image compute time.

Usage:
    python scripts/quality/vif_full_grid_pilot.py [--n-references 100] [--seed-offset 0]
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, fields
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

from ct_iqa.config.loader import random_seed  # noqa: E402
from ct_iqa.data.manifest import read_manifest_csv  # noqa: E402
from ct_iqa.degradation import (  # noqa: E402
    BLUR_SIGMAS,
    Condition,
    NOISE_SIGMAS,
    apply_condition,
    condition_rng,
)
from ct_iqa.utils.paths import resolve  # noqa: E402
from ct_iqa.vif.wavelet import vif_wavelet, vif_wavelet_diagnostics  # noqa: E402

OUTPUT_ROOT = resolve("data/interim/vif_full_grid_pilot")  # gitignored: data/interim/**
IMAGES_DIR = OUTPUT_ROOT / "figures"
RECORDS_PATH = OUTPUT_ROOT / "full_grid_records.csv"
SAMPLE_PATH = OUTPUT_ROOT / "sample_selection.csv"
SUMMARY_PATH = OUTPUT_ROOT / "summary.json"

# PILOT-ONLY provisional choices -- identical to scripts/quality/vif_pilot.py,
# NOT a resolution of U-D01/U-D02 for the full 169,000-image dataset.
PILOT_COMBINATION_ORDER = "blur_then_noise"
PILOT_SIGMA_SCALE = 1.0

# Diagnostic thresholds -- FLAGS, not corrections. Unchanged from the
# 30-reference pilot (docs/vif_pilot_report.md) so the two pilots are
# directly comparable.
CU_COND_FLAG_THRESHOLD = 1e12
G_FLAG_THRESHOLD = 50.0
VIF_UPPER_FLAG_THRESHOLD = 1.5

FIELDNAMES = [
    "reference_id", "degraded_id", "degradation_type", "noise_sigma", "blur_sigma",
    "expert_score", "vif_score", "diagnostic_status", "max_channel_gain",
    "covariance_condition_number",
]


@dataclass
class FullGridRecord:
    reference_id: str
    degraded_id: str
    degradation_type: str
    noise_sigma: float | None
    blur_sigma: float | None
    expert_score: float | None
    vif_score: float
    diagnostic_status: str
    max_channel_gain: float
    covariance_condition_number: float


def load_ldctiqa_references() -> list[dict[str, str]]:
    return read_manifest_csv(resolve("data/manifests/ldctiqa_manifest.csv"))


def select_stratified_sample(
    references: list[dict[str, str]], n: int, seed: int
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    scored = [(r, float(r["label"])) for r in references if r.get("label") not in (None, "")]
    scored.sort(key=lambda t: t[1])

    n_bins = min(5, n)
    bin_edges = np.linspace(0, len(scored), n_bins + 1).astype(int)
    per_bin = n // n_bins
    remainder = n - per_bin * n_bins

    rng = np.random.default_rng(seed)
    selected: list[dict[str, str]] = []
    selection_log: list[dict[str, str]] = []

    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i + 1]
        bin_items = scored[lo:hi]
        take = min(per_bin + (1 if i < remainder else 0), len(bin_items))
        idx = rng.choice(len(bin_items), size=take, replace=False)
        score_lo = bin_items[0][1] if bin_items else float("nan")
        score_hi = bin_items[-1][1] if bin_items else float("nan")
        for j in idx:
            record, score = bin_items[j]
            selected.append(record)
            selection_log.append(
                {
                    "reference_id": record["image_id"],
                    "filename": record.get("filename", f"{record['image_id']}.png"),
                    "expert_score": score,
                    "selection_seed": seed,
                    "selection_reason": (
                        f"stratified_bin_{i+1}_of_{n_bins} "
                        f"(expert_score range [{score_lo:.2f}, {score_hi:.2f}])"
                    ),
                }
            )

    return selected, selection_log


def load_reference_image(ref_row: dict[str, str]) -> np.ndarray:
    from PIL import Image

    path = resolve(ref_row["source_path"])
    with Image.open(path) as im:
        arr = np.array(im, dtype=np.float64)
    if arr.ndim == 3:
        arr = arr[:, :, 0]
    return arr


def build_full_grid_conditions() -> list[Condition]:
    """The COMPLETE Ohashi grid: 12 noise + 12 blur + 144 noise+blur = 168
    conditions (clean excluded -- see report Section 2/3 for the
    accounting reconciliation against Ohashi's reported 169/reference)."""
    conditions: list[Condition] = []
    conditions += [Condition("noise", noise_sigma=float(s)) for s in NOISE_SIGMAS]
    conditions += [Condition("blur", blur_sigma=float(s)) for s in BLUR_SIGMAS]
    conditions += [
        Condition("noise_blur", noise_sigma=float(n), blur_sigma=float(b))
        for n in NOISE_SIGMAS
        for b in BLUR_SIGMAS
    ]
    assert len(conditions) == 168, f"expected 168 conditions, got {len(conditions)}"
    return conditions


def classify_diagnostics(records: list[dict], vif_score: float) -> tuple[str, float, float]:
    flags = []
    if not np.isfinite(vif_score):
        flags.append("NON_FINITE_VIF")
    elif vif_score < 0:
        flags.append("NEGATIVE_VIF")
    elif vif_score > VIF_UPPER_FLAG_THRESHOLD:
        flags.append("VIF_ABOVE_EXPECTED_RANGE")

    max_cu_cond = max((r["cu_condition_number"] for r in records), default=float("nan"))
    max_g = max((r["g_max"] for r in records), default=float("nan"))

    if np.isfinite(max_cu_cond) and max_cu_cond > CU_COND_FLAG_THRESHOLD:
        flags.append("ILL_CONDITIONED_COVARIANCE")
    if np.isfinite(max_g) and max_g > G_FLAG_THRESHOLD:
        flags.append("UNSTABLE_CHANNEL_GAIN")
    if any(not np.isfinite(r["ss_max"]) for r in records):
        flags.append("NON_FINITE_INTERMEDIATE")
    if any(r["ss_max"] <= 1e-10 for r in records):
        flags.append("NEAR_ZERO_VARIANCE_SUBBAND")

    return (";".join(flags) if flags else "ok", max_g, max_cu_cond)


def compute_vif_via_diagnostics(reference: np.ndarray, distorted: np.ndarray) -> tuple[float, list[dict]]:
    """Derive the VIF score from vif_wavelet_diagnostics() rather than
    calling vif_wavelet() separately -- see module docstring. Only valid
    for profile="project" (aggregation="sum"); asserted, not assumed.
    """
    records = vif_wavelet_diagnostics(reference, distorted, profile="project")
    total_num = sum(r["subband_num"] for r in records)
    total_den = sum(r["subband_den"] for r in records)
    score = total_num / total_den if total_den > 0 else float("nan")
    return score, records


def _determinism_check(reference: np.ndarray, distorted: np.ndarray, n: int = 3) -> bool:
    scores = [compute_vif_via_diagnostics(reference, distorted)[0] for _ in range(n)]
    return all(s == scores[0] for s in scores)


def run_full_grid_pilot(n_references: int, seed: int) -> None:
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)

    references = load_ldctiqa_references()
    if not references:
        print("ERROR: LDCT-IQAC manifest not found or empty.")
        sys.exit(2)

    selected, selection_log = select_stratified_sample(references, n_references, seed)
    conditions = build_full_grid_conditions()

    n_noise = len(NOISE_SIGMAS)
    n_blur = len(BLUR_SIGMAS)
    n_combined = n_noise * n_blur
    per_ref_no_clean = n_noise + n_blur + n_combined
    per_ref_with_clean = per_ref_no_clean + 1
    total_no_clean = len(selected) * per_ref_no_clean
    total_with_clean = len(selected) * per_ref_with_clean

    print(f"Selected {len(selected)} reference images (target {n_references}), seed={seed}")
    print(f"Grid accounting: {n_noise} noise + {n_blur} blur + {n_noise}x{n_blur}={n_combined} combined "
          f"= {per_ref_no_clean} conditions/reference (clean excluded)")
    print(f"  with clean reference counted: {per_ref_with_clean} conditions/reference")
    print(f"Theoretical total, {len(selected)} references:")
    print(f"  degraded only (no clean):  {total_no_clean}")
    print(f"  with clean references:     {total_with_clean}")
    print(f"PILOT-ONLY provisional parameters: combination_order={PILOT_COMBINATION_ORDER!r}, "
          f"sigma_scale={PILOT_SIGMA_SCALE}")

    # --- determinism check on a small sample before the full run ---
    probe_ref = load_reference_image(selected[0])
    probe_cond = Condition("noise_blur", noise_sigma=6.0, blur_sigma=1.4)
    probe_rng = condition_rng(seed, selected[0]["image_id"], probe_cond)
    probe_dist = apply_condition(
        probe_ref, probe_cond, order=PILOT_COMBINATION_ORDER, sigma_scale=PILOT_SIGMA_SCALE,
        rng=probe_rng, clip_range=None,
    )
    deterministic = _determinism_check(probe_ref, probe_dist)
    print(f"Determinism check (3x repeat on one probe image): {'PASS' if deterministic else 'FAIL'}")

    # --- disk-usage projection: encode one degraded image as PNG, extrapolate ---
    from PIL import Image
    import io

    sample_u8 = np.clip(probe_dist, 0, 255).astype(np.uint8)
    buf = io.BytesIO()
    Image.fromarray(sample_u8).save(buf, format="PNG")
    sample_png_bytes = buf.tell()
    print(f"Sample degraded-image PNG size: {sample_png_bytes / 1024:.1f} KB "
          f"(pixels are NOT written to disk in this pilot -- see report Section 14 "
          f"for the extrapolated full-dataset storage projection using this figure)")

    all_records: list[FullGridRecord] = []
    example_images: dict[str, tuple[np.ndarray, dict]] = {}

    start_time = time.perf_counter()
    per_image_times: list[float] = []

    with RECORDS_PATH.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=FIELDNAMES)
        writer.writeheader()

        for ref_idx, ref_row in enumerate(selected):
            ref_id = ref_row["image_id"]
            expert_score = float(ref_row["label"]) if ref_row.get("label") not in (None, "") else None
            reference_img = load_reference_image(ref_row)

            for cond in conditions:
                t0 = time.perf_counter()
                rng = condition_rng(seed, ref_id, cond)
                degraded_img = apply_condition(
                    reference_img, cond, order=PILOT_COMBINATION_ORDER,
                    sigma_scale=PILOT_SIGMA_SCALE, rng=rng, clip_range=None,
                )

                degraded_id = f"{ref_id}_{cond.suffix()}"
                try:
                    vif_score, diag_records = compute_vif_via_diagnostics(reference_img, degraded_img)
                    status, max_g, max_cu_cond = classify_diagnostics(diag_records, vif_score)
                except ValueError as exc:
                    vif_score = float("nan")
                    status = f"COMPUTATION_ERROR:{exc}"
                    max_g = max_cu_cond = float("nan")

                elapsed = time.perf_counter() - t0
                per_image_times.append(elapsed)

                record = FullGridRecord(
                    reference_id=ref_id, degraded_id=degraded_id,
                    degradation_type=cond.degradation_type,
                    noise_sigma=cond.noise_sigma, blur_sigma=cond.blur_sigma,
                    expert_score=expert_score, vif_score=vif_score,
                    diagnostic_status=status, max_channel_gain=max_g,
                    covariance_condition_number=max_cu_cond,
                )
                all_records.append(record)
                writer.writerow(asdict(record))

                if ref_idx < 3 and cond.degradation_type in ("noise", "blur", "noise_blur"):
                    key = None
                    if cond.degradation_type == "noise" and cond.noise_sigma in (
                        NOISE_SIGMAS[0], NOISE_SIGMAS[5], NOISE_SIGMAS[-1]
                    ) and ref_idx == 0:
                        key = f"noise_{cond.noise_sigma:g}"
                    elif cond.degradation_type == "blur" and cond.blur_sigma in (
                        BLUR_SIGMAS[0], BLUR_SIGMAS[5], BLUR_SIGMAS[-1]
                    ) and ref_idx == 0:
                        key = f"blur_{cond.blur_sigma:g}"
                    elif (
                        cond.degradation_type == "noise_blur" and ref_idx == 0
                        and cond.noise_sigma in (NOISE_SIGMAS[0], NOISE_SIGMAS[5], NOISE_SIGMAS[-1])
                        and cond.blur_sigma in (BLUR_SIGMAS[0], BLUR_SIGMAS[5], BLUR_SIGMAS[-1])
                    ):
                        key = f"combined_n{cond.noise_sigma:g}_b{cond.blur_sigma:g}"
                    if key:
                        example_images[key] = (
                            degraded_img,
                            {"noise_sigma": cond.noise_sigma, "blur_sigma": cond.blur_sigma,
                             "vif": vif_score, "status": status},
                        )
                    if ref_idx == 0 and "reference" not in example_images:
                        example_images["reference"] = (reference_img, {})

            fh.flush()
            elapsed_total = time.perf_counter() - start_time
            n_done = len(all_records)
            rate = n_done / elapsed_total if elapsed_total > 0 else 0.0
            eta_s = (total_no_clean - n_done) / rate if rate > 0 else float("nan")
            print(f"  ... {ref_idx + 1}/{len(selected)} references, {n_done}/{total_no_clean} images "
                  f"({rate:.2f} img/s, elapsed {elapsed_total/60:.1f} min, ETA {eta_s/60:.1f} min)")

    total_elapsed = time.perf_counter() - start_time
    _write_outputs(selection_log, all_records, example_images, seed, total_elapsed, per_image_times,
                    sample_png_bytes, deterministic, per_ref_no_clean, per_ref_with_clean,
                    total_no_clean, total_with_clean)


def _write_outputs(
    selection_log, all_records, example_images, seed, total_elapsed, per_image_times,
    sample_png_bytes, deterministic, per_ref_no_clean, per_ref_with_clean,
    total_no_clean, total_with_clean,
) -> None:
    with SAMPLE_PATH.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(
            fh, fieldnames=["reference_id", "filename", "expert_score", "selection_seed", "selection_reason"]
        )
        writer.writeheader()
        writer.writerows(selection_log)

    _write_plots(all_records, example_images)
    summary = _summarize(
        all_records, seed, total_elapsed, per_image_times, sample_png_bytes, deterministic,
        per_ref_no_clean, per_ref_with_clean, total_no_clean, total_with_clean,
    )
    with SUMMARY_PATH.open("w", encoding="utf-8") as fh:
        json.dump(summary, fh, indent=2, default=str)

    print(f"\nWrote (gitignored, not committed):\n  {SAMPLE_PATH}\n  {RECORDS_PATH}\n  {SUMMARY_PATH}\n  {IMAGES_DIR}/*.png")
    print("\nSummary:")
    print(json.dumps(summary, indent=2, default=str))


def _monotonicity_1d(all_records, dtype: str) -> dict:
    by_ref: dict[str, list] = defaultdict(list)
    for r in all_records:
        if r.degradation_type == dtype and np.isfinite(r.vif_score):
            by_ref[r.reference_id].append(r)
    sigma_key = "noise_sigma" if dtype == "noise" else "blur_sigma"

    sequences = 0
    violations = 0
    worst = (0.0, None)
    all_violation_locations = []
    for ref_id, records in by_ref.items():
        records_sorted = sorted(records, key=lambda r: getattr(r, sigma_key))
        scores = [r.vif_score for r in records_sorted]
        sigmas = [getattr(r, sigma_key) for r in records_sorted]
        sequences += 1
        has_violation = False
        for i, (a, b) in enumerate(zip(scores, scores[1:])):
            if b > a:
                has_violation = True
                inc = b - a
                all_violation_locations.append(
                    {"reference_id": ref_id, "from_sigma": sigmas[i], "to_sigma": sigmas[i + 1],
                     "increase": round(inc, 4)}
                )
                if inc > worst[0]:
                    worst = (inc, {"reference_id": ref_id, "from_sigma": sigmas[i], "to_sigma": sigmas[i + 1]})
        if has_violation:
            violations += 1

    return {
        "sequences": sequences,
        "violations": violations,
        "pct_fully_monotonic": round(100.0 * (sequences - violations) / sequences, 1) if sequences else float("nan"),
        "n_local_violations": len(all_violation_locations),
        "worst_violation": {"magnitude": round(worst[0], 4), "location": worst[1]},
        "all_violation_locations": all_violation_locations[:20],  # cap for report readability
    }


def _monotonicity_2d(all_records) -> dict:
    """Proper 2D grid analysis for combined degradation: for each fixed
    blur, sweep noise; for each fixed noise, sweep blur. No naive
    sigma-sum ordering."""
    combined = [r for r in all_records if r.degradation_type == "noise_blur" and np.isfinite(r.vif_score)]
    by_ref: dict[str, dict] = defaultdict(dict)
    for r in combined:
        by_ref[r.reference_id][(r.noise_sigma, r.blur_sigma)] = r.vif_score

    noise_levels = sorted(NOISE_SIGMAS)
    blur_levels = sorted(BLUR_SIGMAS)

    fixed_blur_sequences = 0
    fixed_blur_violations = 0
    fixed_noise_sequences = 0
    fixed_noise_violations = 0
    violation_by_fixed_blur = Counter()
    violation_by_fixed_noise = Counter()
    worst = (0.0, None)
    n_local_violations = 0

    for ref_id, grid in by_ref.items():
        for b in blur_levels:
            seq = [grid.get((n, b)) for n in noise_levels]
            if any(v is None for v in seq):
                continue
            fixed_blur_sequences += 1
            has_violation = False
            for i, (a, y) in enumerate(zip(seq, seq[1:])):
                if y > a:
                    has_violation = True
                    n_local_violations += 1
                    inc = y - a
                    if inc > worst[0]:
                        worst = (inc, {"reference_id": ref_id, "fixed_blur": b,
                                        "noise_from": noise_levels[i], "noise_to": noise_levels[i + 1]})
            if has_violation:
                fixed_blur_violations += 1
                violation_by_fixed_blur[b] += 1

        for n in noise_levels:
            seq = [grid.get((n, b)) for b in blur_levels]
            if any(v is None for v in seq):
                continue
            fixed_noise_sequences += 1
            has_violation = False
            for i, (a, y) in enumerate(zip(seq, seq[1:])):
                if y > a:
                    has_violation = True
                    n_local_violations += 1
                    inc = y - a
                    if inc > worst[0]:
                        worst = (inc, {"reference_id": ref_id, "fixed_noise": n,
                                        "blur_from": blur_levels[i], "blur_to": blur_levels[i + 1]})
            if has_violation:
                fixed_noise_violations += 1
                violation_by_fixed_noise[n] += 1

    total_sequences = fixed_blur_sequences + fixed_noise_sequences
    total_violations = fixed_blur_violations + fixed_noise_violations

    return {
        "fixed_blur_sweep_noise": {
            "sequences": fixed_blur_sequences,
            "violations": fixed_blur_violations,
            "pct_fully_monotonic": round(100.0 * (fixed_blur_sequences - fixed_blur_violations) / fixed_blur_sequences, 1)
            if fixed_blur_sequences else float("nan"),
            "violations_by_fixed_blur_sigma": dict(violation_by_fixed_blur),
        },
        "fixed_noise_sweep_blur": {
            "sequences": fixed_noise_sequences,
            "violations": fixed_noise_violations,
            "pct_fully_monotonic": round(100.0 * (fixed_noise_sequences - fixed_noise_violations) / fixed_noise_sequences, 1)
            if fixed_noise_sequences else float("nan"),
            "violations_by_fixed_noise_sigma": dict(violation_by_fixed_noise),
        },
        "overall": {
            "sequences": total_sequences,
            "violations": total_violations,
            "pct_fully_monotonic": round(100.0 * (total_sequences - total_violations) / total_sequences, 1)
            if total_sequences else float("nan"),
            "n_local_violations": n_local_violations,
        },
        "worst_violation": {"magnitude": round(worst[0], 4), "location": worst[1]},
    }


def _channel_gain_analysis(all_records) -> dict:
    by_noise = defaultdict(list)
    by_blur = defaultdict(list)
    for r in all_records:
        if r.degradation_type in ("noise", "noise_blur") and r.noise_sigma is not None:
            by_noise[r.noise_sigma].append(r.max_channel_gain)
        if r.degradation_type in ("blur", "noise_blur") and r.blur_sigma is not None:
            by_blur[r.blur_sigma].append(r.max_channel_gain)

    flagged = [r for r in all_records if "UNSTABLE_CHANNEL_GAIN" in r.diagnostic_status]
    unflagged = [r for r in all_records if "UNSTABLE_CHANNEL_GAIN" not in r.diagnostic_status]

    by_expert_bin = defaultdict(list)
    for r in all_records:
        if r.expert_score is not None:
            bin_key = f"{int(r.expert_score)}-{int(r.expert_score)+1}"
            by_expert_bin[bin_key].append(r.max_channel_gain)

    return {
        "overall_flag_rate_pct": round(100.0 * len(flagged) / len(all_records), 1),
        "mean_max_gain_by_noise_sigma": {str(k): round(float(np.mean(v)), 1) for k, v in sorted(by_noise.items())},
        "mean_max_gain_by_blur_sigma": {str(k): round(float(np.mean(v)), 1) for k, v in sorted(by_blur.items())},
        "mean_max_gain_by_expert_score_bin": {k: round(float(np.mean(v)), 1) for k, v in sorted(by_expert_bin.items())},
        "flagged_vif_stats": {
            "min": round(min((r.vif_score for r in flagged if np.isfinite(r.vif_score)), default=float("nan")), 4),
            "max": round(max((r.vif_score for r in flagged if np.isfinite(r.vif_score)), default=float("nan")), 4),
            "mean": round(float(np.mean([r.vif_score for r in flagged if np.isfinite(r.vif_score)])), 4) if flagged else None,
        },
        "unflagged_vif_stats": {
            "min": round(min((r.vif_score for r in unflagged if np.isfinite(r.vif_score)), default=float("nan")), 4),
            "max": round(max((r.vif_score for r in unflagged if np.isfinite(r.vif_score)), default=float("nan")), 4),
            "mean": round(float(np.mean([r.vif_score for r in unflagged if np.isfinite(r.vif_score)])), 4) if unflagged else None,
        },
    }


def _distribution_stats(values: list[float]) -> dict:
    arr = np.array([v for v in values if np.isfinite(v)])
    if arr.size == 0:
        return {"n": 0}
    return {
        "n": int(arr.size),
        "mean": round(float(np.mean(arr)), 4),
        "median": round(float(np.median(arr)), 4),
        "std": round(float(np.std(arr)), 4),
        "min": round(float(np.min(arr)), 4),
        "max": round(float(np.max(arr)), 4),
        "p5": round(float(np.percentile(arr, 5)), 4),
        "p25": round(float(np.percentile(arr, 25)), 4),
        "p75": round(float(np.percentile(arr, 75)), 4),
        "p95": round(float(np.percentile(arr, 95)), 4),
    }


def _expert_score_association(all_records) -> dict:
    from scipy.stats import pearsonr, spearmanr

    by_ref = defaultdict(list)
    expert = {}
    for r in all_records:
        if r.expert_score is not None and np.isfinite(r.vif_score):
            by_ref[r.reference_id].append(r.vif_score)
            expert[r.reference_id] = r.expert_score

    refs = list(by_ref.keys())
    mean_vif = [float(np.mean(by_ref[r])) for r in refs]
    exp = [expert[r] for r in refs]
    if len(refs) >= 2:
        pr, _ = pearsonr(mean_vif, exp)
        sr, _ = spearmanr(mean_vif, exp)
    else:
        pr = sr = float("nan")
    return {
        "label": "DESCRIPTIVE ASSOCIATION -- NOT SUBJECTIVE VALIDATION",
        "n_references": len(refs),
        "pearson": round(float(pr), 4),
        "spearman": round(float(sr), 4),
    }


def _summarize(
    all_records, seed, total_elapsed, per_image_times, sample_png_bytes, deterministic,
    per_ref_no_clean, per_ref_with_clean, total_no_clean, total_with_clean,
) -> dict:
    vif_scores = np.array([r.vif_score for r in all_records])
    finite_mask = np.isfinite(vif_scores)
    status_counts = Counter(r.diagnostic_status for r in all_records)

    times = np.array(per_image_times)
    n_images = len(all_records)

    projected_full_dataset_gb = (sample_png_bytes * 169000) / 1e9

    return {
        "seed": seed,
        "grid_accounting": {
            "noise_levels": len(NOISE_SIGMAS),
            "blur_levels": len(BLUR_SIGMAS),
            "combined_levels": len(NOISE_SIGMAS) * len(BLUR_SIGMAS),
            "conditions_per_reference_no_clean": per_ref_no_clean,
            "conditions_per_reference_with_clean": per_ref_with_clean,
            "n_references": len({r.reference_id for r in all_records}),
            "theoretical_total_no_clean": total_no_clean,
            "theoretical_total_with_clean": total_with_clean,
            "actual_generated": n_images,
            "ohashi_reported_per_reference": 169,
            "ohashi_reported_total": 105 * 169,
            "reconciliation": (
                "Ohashi's reported 169/reference = 1 clean + 12 noise + 12 blur + 144 combined. "
                "Our 168/reference excludes the clean condition (generated separately, VIF trivially "
                "~1.0, not a distinct degraded-image record). 168 + 1 = 169, matching Ohashi exactly. "
                "No unresolved discrepancy."
            ),
        },
        "vif_validity": {
            "n_generated": n_images,
            "n_vif_success": int(finite_mask.sum()),
            "n_nan": int(np.isnan(vif_scores).sum()),
            "n_inf": int(np.isinf(vif_scores).sum()),
            "n_negative": int(np.sum(vif_scores[finite_mask] < 0)),
            "n_above_1.5": int(np.sum(vif_scores[finite_mask] > VIF_UPPER_FLAG_THRESHOLD)),
            "status_counts": dict(status_counts),
        },
        "determinism_check_passed": deterministic,
        "monotonicity": {
            "noise": _monotonicity_1d(all_records, "noise"),
            "blur": _monotonicity_1d(all_records, "blur"),
            "combined_2d": _monotonicity_2d(all_records),
        },
        "channel_gain_analysis": _channel_gain_analysis(all_records),
        "vif_distribution": {
            "all": _distribution_stats(list(vif_scores)),
            "noise_only": _distribution_stats([r.vif_score for r in all_records if r.degradation_type == "noise"]),
            "blur_only": _distribution_stats([r.vif_score for r in all_records if r.degradation_type == "blur"]),
            "combined": _distribution_stats([r.vif_score for r in all_records if r.degradation_type == "noise_blur"]),
        },
        "expert_score_association": _expert_score_association(all_records),
        "performance": {
            "total_runtime_seconds": round(total_elapsed, 1),
            "total_runtime_minutes": round(total_elapsed / 60, 2),
            "n_images": n_images,
            "mean_seconds_per_image": round(float(np.mean(times)), 4),
            "median_seconds_per_image": round(float(np.median(times)), 4),
            "images_per_second": round(n_images / total_elapsed, 3),
            "sample_degraded_png_kb": round(sample_png_bytes / 1024, 1),
            "projected_full_169k_dataset_storage_gb": round(projected_full_dataset_gb, 2),
            "projected_full_169k_runtime_hours": round((169000 / (n_images / total_elapsed)) / 3600, 2),
        },
    }


def _write_plots(all_records, example_images) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    vif_scores = np.array([r.vif_score for r in all_records])
    finite = vif_scores[np.isfinite(vif_scores)]

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(finite, bins=50)
    ax.set_xlabel("VIF score (project profile)")
    ax.set_ylabel("count")
    ax.set_title(f"VIF distribution, full-grid pilot (n={len(finite)})")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_histogram.png", dpi=100)
    plt.close(fig)

    by_type: dict[str, list[float]] = defaultdict(list)
    for r in all_records:
        if np.isfinite(r.vif_score):
            by_type[r.degradation_type].append(r.vif_score)
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.boxplot(list(by_type.values()), tick_labels=list(by_type.keys()))
    ax.set_ylabel("VIF score")
    ax.set_title("VIF by degradation type")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_by_degradation_type.png", dpi=100)
    plt.close(fig)

    combined = [r for r in all_records if r.degradation_type == "noise_blur" and np.isfinite(r.vif_score)]
    if combined:
        noise_idx = {s: i for i, s in enumerate(sorted(NOISE_SIGMAS))}
        blur_idx = {s: i for i, s in enumerate(sorted(BLUR_SIGMAS))}
        grid = np.full((len(noise_idx), len(blur_idx)), np.nan)
        counts = np.zeros_like(grid)
        for r in combined:
            i, j = noise_idx[r.noise_sigma], blur_idx[r.blur_sigma]
            if np.isnan(grid[i, j]):
                grid[i, j] = 0.0
            grid[i, j] += r.vif_score
            counts[i, j] += 1
        grid = np.divide(grid, counts, out=grid, where=counts > 0)
        fig, ax = plt.subplots(figsize=(7, 6))
        im = ax.imshow(grid, aspect="auto", origin="lower", cmap="viridis")
        ax.set_xticks(range(len(blur_idx)))
        ax.set_xticklabels([f"{s:g}" for s in sorted(BLUR_SIGMAS)], rotation=45)
        ax.set_yticks(range(len(noise_idx)))
        ax.set_yticklabels([f"{s:g}" for s in sorted(NOISE_SIGMAS)])
        ax.set_xlabel("blur sigma")
        ax.set_ylabel("noise sigma")
        ax.set_title("Mean VIF, full 12x12 combined grid (avg over references)")
        fig.colorbar(im, ax=ax, label="mean VIF")
        fig.tight_layout()
        fig.savefig(IMAGES_DIR / "vif_combined_grid_heatmap.png", dpi=100)
        plt.close(fig)

    if example_images:
        order = [k for k in example_images if k != "reference"]
        order = ["reference"] + order if "reference" in example_images else order
        n = len(order)
        fig, axes = plt.subplots(1, n, figsize=(3 * n, 3.2))
        if n == 1:
            axes = [axes]
        for ax, key in zip(axes, order):
            img, meta = example_images[key]
            ax.imshow(img, cmap="gray", vmin=0, vmax=255)
            title = key
            if meta:
                title += f"\nVIF={meta['vif']:.3f}\n{meta['status'][:20]}"
            ax.set_title(title, fontsize=7)
            ax.axis("off")
        fig.tight_layout()
        fig.savefig(IMAGES_DIR / "example_grid.png", dpi=100)
        plt.close(fig)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n-references", type=int, default=100)
    parser.add_argument("--seed-offset", type=int, default=0)
    args = parser.parse_args()
    run_full_grid_pilot(args.n_references, random_seed() + args.seed_offset)
