"""Small-pilot validation of the canonical VIF pipeline on real LDCT-IQAC images.

Selects ~20-50 real LDCT-IQAC reference images (stratified across the
expert_score range), applies the Ohashi degradation grid to each using the
project's canonical degradation engine, computes VIF with the canonical
`vif_wavelet(profile="project")`, runs per-image diagnostics, and analyses
monotonicity, distribution, and low-texture instability -- to answer one
question before any full-scale generation: does the validated-but-not-
MATLAB-verified VIF implementation behave sanely on real CT images, not
just synthetic test patterns?

Does NOT generate the 169,000-image dataset, does NOT write to
data/manifests/quality_iqa_manifest.*, does NOT modify
data/raw/ldctiqa/ground_truth_score.json, and does NOT train anything.
All generated pixels/plots are written under data/interim/vif_pilot/,
which is covered by the project's .gitignore (`data/interim/**`) --
nothing generated by this script is committed.

Two parameters this pilot must supply that the canonical dataset
generator (scripts/quality/build_ohashi_dataset.py) deliberately refuses
to guess -- combined-degradation order and noise sigma_scale -- are given
explicit, clearly-labelled PILOT-ONLY provisional values below. This does
NOT resolve U-D01/U-D02 in docs/research_decisions.md for the full
dataset; that remains open and separately gated.

Usage:
    python scripts/quality/vif_pilot.py [--n-references 30] [--seed-offset 0]
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

from ct_iqa.config.loader import load_config, random_seed  # noqa: E402
from ct_iqa.data.manifest import read_manifest_csv  # noqa: E402
from ct_iqa.degradation import (  # noqa: E402
    BLUR_SIGMAS,
    Condition,
    NOISE_SIGMAS,
    apply_condition,
    condition_rng,
)
from ct_iqa.utils.paths import resolve  # noqa: E402
from ct_iqa.vif.wavelet import vif_wavelet, vif_wavelet_diagnostics  # noqa: E402

OUTPUT_ROOT = resolve("data/interim/vif_pilot")  # gitignored: data/interim/**
IMAGES_DIR = OUTPUT_ROOT / "figures"
RECORDS_PATH = OUTPUT_ROOT / "pilot_records.csv"
SAMPLE_PATH = OUTPUT_ROOT / "sample_selection.csv"
DIAGNOSTICS_PATH = OUTPUT_ROOT / "diagnostics_summary.json"

# PILOT-ONLY provisional choices -- see module docstring. NOT a resolution
# of U-D01/U-D02 for the full 169,000-image dataset.
PILOT_COMBINATION_ORDER = "blur_then_noise"
PILOT_SIGMA_SCALE = 1.0

# Combined (noise+blur) grid is reduced to a 3x3 low/medium/high subset for
# this pilot -- the full 12x12=144 factorial per reference would take the
# pilot from ~34 to ~169 images per reference (30x more VIF evaluations,
# each ~1-1.5s at 512x512) for marginal additional monotonicity signal.
# Noise-only and blur-only use the FULL 12-level OHASHI-SPECIFIED grids,
# unreduced. This reduction applies ONLY to this pilot script -- the actual
# dataset generator (build_ohashi_dataset.py) still targets the full 144
# combined conditions per reference per configs/quality/ohashi_ldctiqac.yaml.
REPRESENTATIVE_NOISE = (NOISE_SIGMAS[0], NOISE_SIGMAS[5], NOISE_SIGMAS[-1])  # 1, 6, 50
REPRESENTATIVE_BLUR = (BLUR_SIGMAS[0], BLUR_SIGMAS[5], BLUR_SIGMAS[-1])  # 0.1, 0.6, 5.0

# Diagnostic thresholds -- FLAGS, not corrections. Chosen from the smooth-
# image investigation in docs/vif_implementation.md sec 13.4 (cu_cond there
# was ~1e16-1e18 for the known-unstable case; g there reached ~2212).
CU_COND_FLAG_THRESHOLD = 1e12
G_FLAG_THRESHOLD = 50.0
VIF_UPPER_FLAG_THRESHOLD = 1.5  # VIF for real distortion is expected in ~[0, 1]


@dataclass
class PilotRecord:
    reference_id: str
    degraded_id: str
    degradation_type: str
    noise_sigma: float | None
    blur_sigma: float | None
    expert_score: float | None
    vif_score: float
    diagnostic_status: str
    max_cu_cond: float
    max_g: float
    min_eigenvalue: float


def load_ldctiqa_references() -> list[dict[str, str]]:
    manifest_path = resolve("data/manifests/ldctiqa_manifest.csv")
    return read_manifest_csv(manifest_path)


def select_stratified_sample(
    references: list[dict[str, str]], n: int, seed: int
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Stratified-by-expert_score sample, reproducible from `seed`.

    Returns (selected_references, selection_log) where selection_log has one
    row per selected image recording image_id/expert_score/selection_reason/
    random_seed, matching the required record fields exactly.
    """
    scored = [(r, float(r["label"])) for r in references if r.get("label") not in (None, "")]
    scored.sort(key=lambda t: t[1])

    n_bins = min(5, n)
    bin_edges = np.linspace(0, len(scored), n_bins + 1).astype(int)
    per_bin = n // n_bins
    remainder = n - per_bin * n_bins

    rng = np.random.default_rng(seed)
    selected: list[dict[str, str]] = []
    selection_log: list[dict[str, str]] = []

    for i in range(n_bins):
        lo, hi = bin_edges[i], bin_edges[i + 1]
        bin_items = scored[lo:hi]
        take = per_bin + (1 if i < remainder else 0)
        take = min(take, len(bin_items))
        idx = rng.choice(len(bin_items), size=take, replace=False)
        score_lo = bin_items[0][1] if bin_items else float("nan")
        score_hi = bin_items[-1][1] if bin_items else float("nan")
        for j in idx:
            record, score = bin_items[j]
            selected.append(record)
            selection_log.append(
                {
                    "image_id": record["image_id"],
                    "expert_score": score,
                    "selection_reason": (
                        f"stratified_bin_{i+1}_of_{n_bins} "
                        f"(expert_score range [{score_lo:.2f}, {score_hi:.2f}])"
                    ),
                    "random_seed": seed,
                }
            )

    return selected, selection_log


def load_reference_image(ref_row: dict[str, str]) -> np.ndarray:
    """Load one LDCT-IQAC reference image as a 2-D float64 array.

    Source images are RGB PNGs with three verified-identical channels
    (see configs/datasets/ldctiqa.yaml). Channel 0 is used directly rather
    than averaging across channels -- since they are identical, averaging
    would only add float rounding noise for no benefit. The original file
    on disk is opened read-only and never written back to.
    """
    from PIL import Image

    path = resolve(ref_row["source_path"])
    with Image.open(path) as im:
        arr = np.array(im, dtype=np.float64)
    if arr.ndim == 3:
        arr = arr[:, :, 0]
    return arr


def build_pilot_conditions() -> list[Condition]:
    conditions: list[Condition] = [Condition("clean")]
    conditions += [Condition("noise", noise_sigma=float(s)) for s in NOISE_SIGMAS]
    conditions += [Condition("blur", blur_sigma=float(s)) for s in BLUR_SIGMAS]
    conditions += [
        Condition("noise_blur", noise_sigma=float(n), blur_sigma=float(b))
        for n in REPRESENTATIVE_NOISE
        for b in REPRESENTATIVE_BLUR
    ]
    return conditions


def classify_diagnostics(records: list[dict], vif_score: float) -> tuple[str, float, float, float]:
    """Inspect per-subband diagnostics and the final score; return
    (status, max_cu_cond, max_g, min_eigenvalue). status is one or more
    flags joined by ';', or 'ok'."""
    flags = []
    if not np.isfinite(vif_score):
        flags.append("NON_FINITE_VIF")
    elif vif_score < 0:
        flags.append("NEGATIVE_VIF")
    elif vif_score > VIF_UPPER_FLAG_THRESHOLD:
        flags.append("VIF_ABOVE_EXPECTED_RANGE")

    max_cu_cond = max((r["cu_condition_number"] for r in records), default=float("nan"))
    max_g = max((r["g_max"] for r in records), default=float("nan"))
    min_eig = min((r["eigenvalue_min"] for r in records), default=float("nan"))

    if np.isfinite(max_cu_cond) and max_cu_cond > CU_COND_FLAG_THRESHOLD:
        flags.append("ILL_CONDITIONED_COVARIANCE")
    if np.isfinite(max_g) and max_g > G_FLAG_THRESHOLD:
        flags.append("UNSTABLE_CHANNEL_GAIN")
    if any(not np.isfinite(r["ss_max"]) for r in records):
        flags.append("NON_FINITE_INTERMEDIATE")
    if any(r["ss_max"] <= 1e-10 for r in records):
        flags.append("NEAR_ZERO_VARIANCE_SUBBAND")

    return (";".join(flags) if flags else "ok", max_cu_cond, max_g, min_eig)


def run_pilot(n_references: int, seed: int) -> None:
    IMAGES_DIR.mkdir(parents=True, exist_ok=True)

    references = load_ldctiqa_references()
    if not references:
        print("ERROR: LDCT-IQAC manifest not found or empty; run scripts/build_manifest.py first.")
        sys.exit(2)

    selected, selection_log = select_stratified_sample(references, n_references, seed)
    print(f"Selected {len(selected)} reference images (target {n_references}), seed={seed}")

    conditions = build_pilot_conditions()
    print(f"Conditions per reference: {len(conditions)} "
          f"(1 clean + {len(NOISE_SIGMAS)} noise + {len(BLUR_SIGMAS)} blur + "
          f"{len(REPRESENTATIVE_NOISE) * len(REPRESENTATIVE_BLUR)} combined [reduced])")
    print(f"Expected total generated images: {len(selected) * (len(conditions) - 1)} "
          f"(clean excluded from VIF computation -- VIF of a reference against itself is trivially ~1.0)")
    print(f"PILOT-ONLY provisional parameters: combination_order={PILOT_COMBINATION_ORDER!r}, "
          f"sigma_scale={PILOT_SIGMA_SCALE}")

    all_records: list[PilotRecord] = []
    all_diagnostics_flat: list[dict] = []
    example_images: dict[str, np.ndarray] = {}

    for ref_idx, ref_row in enumerate(selected):
        ref_id = ref_row["image_id"]
        expert_score = float(ref_row["label"]) if ref_row.get("label") not in (None, "") else None
        reference_img = load_reference_image(ref_row)

        if ref_idx == 0:
            example_images["reference"] = reference_img

        for cond in conditions:
            if cond.degradation_type == "clean":
                continue

            rng = condition_rng(seed, ref_id, cond)
            degraded_img = apply_condition(
                reference_img,
                cond,
                order=PILOT_COMBINATION_ORDER,
                sigma_scale=PILOT_SIGMA_SCALE,
                rng=rng,
                clip_range=None,
            )

            degraded_id = f"{ref_id}_{cond.suffix()}"
            try:
                vif_score = vif_wavelet(reference_img, degraded_img, profile="project")
                diag_records = vif_wavelet_diagnostics(reference_img, degraded_img, profile="project")
                status, max_cu_cond, max_g, min_eig = classify_diagnostics(diag_records, vif_score)
                for d in diag_records:
                    d["reference_id"] = ref_id
                    d["degraded_id"] = degraded_id
                    all_diagnostics_flat.append(d)
            except ValueError as exc:
                vif_score = float("nan")
                status = f"COMPUTATION_ERROR:{exc}"
                max_cu_cond = max_g = min_eig = float("nan")

            all_records.append(
                PilotRecord(
                    reference_id=ref_id,
                    degraded_id=degraded_id,
                    degradation_type=cond.degradation_type,
                    noise_sigma=cond.noise_sigma,
                    blur_sigma=cond.blur_sigma,
                    expert_score=expert_score,
                    vif_score=vif_score,
                    diagnostic_status=status,
                    max_cu_cond=max_cu_cond,
                    max_g=max_g,
                    min_eigenvalue=min_eig,
                )
            )

            if ref_idx == 0 and cond.degradation_type == "noise" and cond.noise_sigma in (
                NOISE_SIGMAS[0], NOISE_SIGMAS[5], NOISE_SIGMAS[-1]
            ):
                example_images[f"noise_{cond.noise_sigma:g}"] = degraded_img
            if ref_idx == 0 and cond.degradation_type == "blur" and cond.blur_sigma in (
                BLUR_SIGMAS[0], BLUR_SIGMAS[5], BLUR_SIGMAS[-1]
            ):
                example_images[f"blur_{cond.blur_sigma:g}"] = degraded_img
            if (
                ref_idx == 0
                and cond.degradation_type == "noise_blur"
                and cond.noise_sigma == REPRESENTATIVE_NOISE[0]
                and cond.blur_sigma in REPRESENTATIVE_BLUR
            ):
                example_images[f"combined_n{cond.noise_sigma:g}_b{cond.blur_sigma:g}"] = degraded_img

        if (ref_idx + 1) % 5 == 0 or ref_idx == len(selected) - 1:
            print(f"  ... {ref_idx + 1}/{len(selected)} references processed "
                  f"({len(all_records)} images so far)")

    _write_outputs(selected, selection_log, all_records, all_diagnostics_flat, example_images, seed)


def _write_outputs(
    selected: list[dict],
    selection_log: list[dict],
    all_records: list[PilotRecord],
    all_diagnostics_flat: list[dict],
    example_images: dict[str, np.ndarray],
    seed: int,
) -> None:
    import csv

    with SAMPLE_PATH.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=["image_id", "expert_score", "selection_reason", "random_seed"])
        writer.writeheader()
        writer.writerows(selection_log)

    with RECORDS_PATH.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(asdict(all_records[0]).keys()))
        writer.writeheader()
        for r in all_records:
            writer.writerow(asdict(r))

    _write_plots(all_records, example_images)
    summary = _summarize(all_records, all_diagnostics_flat, seed)
    with DIAGNOSTICS_PATH.open("w", encoding="utf-8") as fh:
        json.dump(summary, fh, indent=2, default=str)

    print(f"\nWrote (gitignored, not committed):")
    print(f"  {SAMPLE_PATH}")
    print(f"  {RECORDS_PATH}")
    print(f"  {DIAGNOSTICS_PATH}")
    print(f"  {IMAGES_DIR}/*.png")
    print("\nSummary:")
    print(json.dumps(summary, indent=2, default=str))


def _write_plots(all_records: list[PilotRecord], example_images: dict[str, np.ndarray]) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    vif_scores = np.array([r.vif_score for r in all_records])
    finite = vif_scores[np.isfinite(vif_scores)]

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(finite, bins=40)
    ax.set_xlabel("VIF score (project profile)")
    ax.set_ylabel("count")
    ax.set_title(f"VIF distribution, pilot sample (n={len(finite)} finite of {len(vif_scores)})")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_histogram.png", dpi=100)
    plt.close(fig)

    by_type: dict[str, list[float]] = {}
    for r in all_records:
        if np.isfinite(r.vif_score):
            by_type.setdefault(r.degradation_type, []).append(r.vif_score)
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.boxplot(list(by_type.values()), tick_labels=list(by_type.keys()))
    ax.set_ylabel("VIF score")
    ax.set_title("VIF by degradation type")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_by_degradation_type.png", dpi=100)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6, 4))
    noise_pts = [(r.noise_sigma, r.vif_score) for r in all_records
                 if r.degradation_type == "noise" and np.isfinite(r.vif_score)]
    if noise_pts:
        xs, ys = zip(*noise_pts)
        ax.scatter(xs, ys, alpha=0.4, s=10)
    ax.set_xlabel("noise sigma")
    ax.set_ylabel("VIF score")
    ax.set_title("VIF vs noise sigma (all references)")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_vs_noise_sigma.png", dpi=100)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6, 4))
    blur_pts = [(r.blur_sigma, r.vif_score) for r in all_records
                if r.degradation_type == "blur" and np.isfinite(r.vif_score)]
    if blur_pts:
        xs, ys = zip(*blur_pts)
        ax.scatter(xs, ys, alpha=0.4, s=10)
    ax.set_xlabel("blur sigma")
    ax.set_ylabel("VIF score")
    ax.set_title("VIF vs blur sigma (all references)")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_vs_blur_sigma.png", dpi=100)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6, 4))
    combined_pts = [(r.noise_sigma + r.blur_sigma, r.vif_score) for r in all_records
                    if r.degradation_type == "noise_blur" and np.isfinite(r.vif_score)]
    if combined_pts:
        xs, ys = zip(*combined_pts)
        ax.scatter(xs, ys, alpha=0.4, s=10)
    ax.set_xlabel("noise_sigma + blur_sigma (combined severity proxy)")
    ax.set_ylabel("VIF score")
    ax.set_title("VIF vs combined degradation severity")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_vs_combined.png", dpi=100)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6, 4))
    by_ref: dict[str, tuple[float, list[float]]] = {}
    for r in all_records:
        if r.expert_score is not None and np.isfinite(r.vif_score):
            by_ref.setdefault(r.reference_id, (r.expert_score, []))[1].append(r.vif_score)
    if by_ref:
        xs = [v[0] for v in by_ref.values()]
        ys = [float(np.mean(v[1])) for v in by_ref.values()]
        ax.scatter(xs, ys, alpha=0.6)
    ax.set_xlabel("LDCT-IQAC expert_score (of the clean reference)")
    ax.set_ylabel("mean VIF score across all degraded variants")
    ax.set_title("VIF vs expert_score -- NOT expected to be equivalent")
    fig.tight_layout()
    fig.savefig(IMAGES_DIR / "vif_vs_expert_score.png", dpi=100)
    plt.close(fig)

    if example_images:
        order = [k for k in [
            "reference",
            f"noise_{NOISE_SIGMAS[0]:g}", f"noise_{NOISE_SIGMAS[5]:g}", f"noise_{NOISE_SIGMAS[-1]:g}",
            f"blur_{BLUR_SIGMAS[0]:g}", f"blur_{BLUR_SIGMAS[5]:g}", f"blur_{BLUR_SIGMAS[-1]:g}",
        ] + [f"combined_n{REPRESENTATIVE_NOISE[0]:g}_b{b:g}" for b in REPRESENTATIVE_BLUR]
                 if k in example_images]
        n = len(order)
        fig, axes = plt.subplots(1, n, figsize=(3 * n, 3))
        if n == 1:
            axes = [axes]
        for ax, key in zip(axes, order):
            ax.imshow(example_images[key], cmap="gray", vmin=0, vmax=255)
            ax.set_title(key, fontsize=8)
            ax.axis("off")
        fig.tight_layout()
        fig.savefig(IMAGES_DIR / "example_grid.png", dpi=100)
        plt.close(fig)


def _monotonicity_report(all_records: list[PilotRecord]) -> dict:
    by_ref_type: dict[tuple[str, str], list[PilotRecord]] = {}
    for r in all_records:
        if r.degradation_type in ("noise", "blur") and np.isfinite(r.vif_score):
            by_ref_type.setdefault((r.reference_id, r.degradation_type), []).append(r)

    results = {"noise": {"sequences": 0, "violations": 0, "worst": None}, "blur": {"sequences": 0, "violations": 0, "worst": None}}
    worst_by_type: dict[str, tuple[float, str]] = {}

    for (ref_id, dtype), records in by_ref_type.items():
        sigma_key = "noise_sigma" if dtype == "noise" else "blur_sigma"
        records_sorted = sorted(records, key=lambda r: getattr(r, sigma_key))
        scores = [r.vif_score for r in records_sorted]
        results[dtype]["sequences"] += 1
        local_violations = 0
        max_increase = 0.0
        for a, b in zip(scores, scores[1:]):
            if b > a:
                local_violations += 1
                max_increase = max(max_increase, b - a)
        if local_violations:
            results[dtype]["violations"] += 1
        if max_increase > worst_by_type.get(dtype, (0.0, ""))[0]:
            worst_by_type[dtype] = (max_increase, ref_id)

    for dtype in ("noise", "blur"):
        seq = results[dtype]["sequences"]
        viol = results[dtype]["violations"]
        results[dtype]["pct_fully_monotonic"] = round(100.0 * (seq - viol) / seq, 1) if seq else float("nan")
        results[dtype]["worst"] = {
            "reference_id": worst_by_type.get(dtype, (0.0, None))[1],
            "max_local_increase": round(worst_by_type.get(dtype, (0.0, None))[0], 4),
        }

    combined = [r for r in all_records if r.degradation_type == "noise_blur" and np.isfinite(r.vif_score)]
    by_ref: dict[str, list[PilotRecord]] = {}
    for r in combined:
        by_ref.setdefault(r.reference_id, []).append(r)
    combined_violations = 0
    combined_sequences = 0
    for ref_id, records in by_ref.items():
        records_sorted = sorted(records, key=lambda r: r.noise_sigma + r.blur_sigma)
        scores = [r.vif_score for r in records_sorted]
        combined_sequences += 1
        if any(b > a for a, b in zip(scores, scores[1:])):
            combined_violations += 1
    results["combined"] = {
        "sequences": combined_sequences,
        "violations": combined_violations,
        "pct_fully_monotonic": round(100.0 * (combined_sequences - combined_violations) / combined_sequences, 1)
        if combined_sequences else float("nan"),
    }
    return results


def _summarize(all_records: list[PilotRecord], all_diagnostics_flat: list[dict], seed: int) -> dict:
    vif_scores = np.array([r.vif_score for r in all_records])
    finite_mask = np.isfinite(vif_scores)
    status_counts = Counter(r.diagnostic_status for r in all_records)
    flagged = [r for r in all_records if r.diagnostic_status != "ok"]

    return {
        "seed": seed,
        "n_references": len({r.reference_id for r in all_records}),
        "n_generated_images": len(all_records),
        "n_vif_success": int(finite_mask.sum()),
        "n_nan": int(np.isnan(vif_scores).sum()),
        "n_inf": int(np.isinf(vif_scores).sum()),
        "n_flagged_abnormal": len(flagged),
        "status_counts": dict(status_counts),
        "vif_stats_finite": {
            "min": float(np.min(vif_scores[finite_mask])) if finite_mask.any() else None,
            "max": float(np.max(vif_scores[finite_mask])) if finite_mask.any() else None,
            "mean": float(np.mean(vif_scores[finite_mask])) if finite_mask.any() else None,
            "median": float(np.median(vif_scores[finite_mask])) if finite_mask.any() else None,
        },
        "monotonicity": _monotonicity_report(all_records),
        "low_texture_diagnostics": {
            "n_subband_records": len(all_diagnostics_flat),
            "n_ill_conditioned_gt_1e12": sum(
                1 for d in all_diagnostics_flat if d["cu_condition_number"] > CU_COND_FLAG_THRESHOLD
            ),
            "n_unstable_gain_gt_50": sum(1 for d in all_diagnostics_flat if d["g_max"] > G_FLAG_THRESHOLD),
            "max_cu_cond_observed": max((d["cu_condition_number"] for d in all_diagnostics_flat), default=None),
            "max_g_observed": max((d["g_max"] for d in all_diagnostics_flat), default=None),
        },
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n-references", type=int, default=30)
    parser.add_argument("--seed-offset", type=int, default=0)
    args = parser.parse_args()
    run_pilot(args.n_references, random_seed() + args.seed_offset)
