"""Generator for notebooks/03_training/01_resnet50_baseline.ipynb.

Run this script to (re)build the notebook from the cell definitions below.
Not part of the `ct_iqa` package -- a dev-time notebook-generation tool.

This notebook covers ONLY training-stage work (config -> data -> model ->
training -> checkpoint). Held-out test-set evaluation lives in the separate
`notebooks/04_evaluation/01_test_set_evaluation.ipynb`, generated by
`tools/build_evaluation_notebook.py`, which loads this notebook's saved
checkpoint from disk rather than sharing in-memory state.

Split out of the single, previous notebooks/02_ohashi_resnet50_ldct_iqac.ipynb
(see docs/repository_architecture_audit.md, section 5): that notebook's
markdown narrative was previously written but never inserted into the
notebook (a `def md(text): pass` no-op) -- this generator restores it as
real markdown cells.
"""

from pathlib import Path

import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []


def md(text):
    cells.append(nbf.v4.new_markdown_cell(text))


def code(text):
    cells.append(nbf.v4.new_code_cell(text))


# Objective
md(
    """# Training -- Ohashi ResNet50 Baseline on LDCT-IQAC

## Objective

Train the **first baseline** from:

> Ohashi et al., *"Development of a No-Reference CT Image Quality Assessment
> Method Using RadImageNet Pre-trained Deep Learning Models."*

Specifically: a **RadImageNet-pretrained ResNet50**, with its classification
head replaced by `Dropout -> Dense(1) -> Sigmoid`, trained as a CT image
quality **regressor** on the **LDCT-IQAC** dataset.

**Scope guardrails for this notebook:**
- No project novelty is implemented here; no InceptionResNetV2.
- All architecture/data/preprocessing/training code lives in the `ct_iqa`
  package (`src/ct_iqa/`) and is only **imported** below -- this notebook is
  an experiment runner, not an implementation surface (see
  `docs/repository_architecture_audit.md`, Rules 1-3).
- Held-out test-set evaluation is a **separate notebook**
  (`notebooks/04_evaluation/01_test_set_evaluation.ipynb`) that loads this
  run's checkpoint from `experiments/001_resnet50_baseline/checkpoint/` --
  it does not rely on this notebook's in-memory state.

**Known deviations from the paper/task brief** (see
`docs/replication/deviations.md` for the full list): LDCT-IQAC images are
TIFF (not PNG); the regression target is LDCT-IQAC's radiologist quality
score (not the paper's VIF metric); no synthetic degradation pipeline is
used (LDCT-IQAC already varies in real quality); the Dropout probability is
not specified by the paper and is an explicit, documented choice here."""
)

# Configuration
md(
    """## Configuration

Loaded from `configs/dataset.yaml` + `configs/preprocessing.yaml` +
`configs/model.yaml` + `configs/training.yaml` via
`ExperimentConfig.from_yaml_files()` -- this is the single authoritative
configuration source (see `src/ct_iqa/config.py`); no dataset/hyperparameter
values are hardcoded separately in this notebook.

`radimagenet_weights_path` is `null` in `configs/model.yaml`: **verified
RadImageNet weights are not currently confirmed present in this
repository** (see `weights/pretrained/radimagenet/resnet50/README.md`).
This run therefore uses random backbone initialization and is reported
honestly as such -- **not** a full replication of the paper's
RadImageNet-pretrained result -- rather than silently substituting
unverified third-party weights."""
)
code(
    """import os
import sys
from pathlib import Path

_cwd = Path.cwd()
_repo_root = _cwd if (_cwd / "data").exists() else _cwd.parent.parent  # notebooks/03_training/ -> repo root
os.chdir(_repo_root)
if str(_repo_root / "src") not in sys.path:
    sys.path.insert(0, str(_repo_root / "src"))  # only needed until `pip install -e .` is run
print(f"repo root: {_repo_root}")"""
)
code(
    """import json
import logging

import matplotlib.pyplot as plt
import torch

from ct_iqa.config import ExperimentConfig
from ct_iqa.data.ldct_iqac import LDCTIQACDataset, SCORE_MIN, SCORE_MAX
from ct_iqa.data.loader import build_dataloaders, build_test_dataloader
from ct_iqa.models.ohashi_resnet50 import OhashiResNet50, INPUT_SIZE
from ct_iqa.training.trainer import evaluate_loader, train
from ct_iqa.training.losses import build_loss
from ct_iqa.training.optimizers import build_optimizer
from ct_iqa.utils.seed import set_seed

logging.basicConfig(level=logging.INFO)
%matplotlib inline

print(f"torch: {torch.__version__}  cuda available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"device: {torch.cuda.get_device_name(0)}")"""
)
code(
    """config = ExperimentConfig.from_yaml_files(
    device="cuda" if torch.cuda.is_available() else "cpu",
)
set_seed(config.seed)
print(f"experiment_dir  : {config.experiment_dir}")
print(f"checkpoint_dir  : {config.checkpoint_dir}")
config"""
)

# Data
md(
    """## Data

Dataset construction itself performs the audit: it fails loudly if any
image has no label, any label has no image, the JSON is malformed, or an
unsupported image mode is encountered. The validation split is created
**only from the training set** (`ct_iqa.data.splits.train_val_split`,
`val_fraction` from `configs/dataset.yaml`) -- the official test set is
never used for model selection; `build_test_dataloader` is a separate,
independent loader used only in the evaluation notebook."""
)
code(
    """for p in [config.train_image_dir, config.train_json_path, config.test_image_dir, config.test_json_path]:
    assert Path(p).exists(), f"missing: {p}"

train_dataset = LDCTIQACDataset(config.train_image_dir, config.train_json_path, image_size=config.image_size)
test_dataset = LDCTIQACDataset(config.test_image_dir, config.test_json_path, image_size=config.image_size)

print(f"training samples: {len(train_dataset)}")
print(f"testing samples : {len(test_dataset)}")
print(f"score range (dataset constants): [{SCORE_MIN}, {SCORE_MAX}]")
print(f"observed train score range: [{min(train_dataset.raw_scores)}, {max(train_dataset.raw_scores)}]")"""
)
code(
    """train_loader, val_loader = build_dataloaders(config)
test_loader = build_test_dataloader(config)  # held out; not used again until the evaluation notebook

print(f"train batches: {len(train_loader)}  ({len(train_loader.dataset)} samples)")
print(f"val batches  : {len(val_loader)}  ({len(val_loader.dataset)} samples)")"""
)
code(
    """fig, axes = plt.subplots(1, 5, figsize=(15, 3))
for i, ax in enumerate(axes):
    image, score = train_dataset[i]
    ax.imshow(image.squeeze(0).numpy(), cmap="gray")
    ax.set_title(f"score={float(score):.2f}")
    ax.axis("off")
plt.suptitle("LDCT-IQAC training samples (center-cropped to model input size)")
plt.tight_layout()
plt.show()"""
)

# Model
md(
    """## Model

`OhashiResNet50` = `ResNet50Backbone` (from-scratch standard ResNet50,
since `torchvision` is not installed in this environment) + `Dropout` +
`Dense(1)` + `Sigmoid`, per the Ohashi paper's stated modification. The
architecture is defined entirely in `src/ct_iqa/models/` -- this notebook
only instantiates and configures it."""
)
code(
    """model = OhashiResNet50(dropout_p=config.dropout_p, in_channels=config.in_channels)
model.to(config.device)

if config.radimagenet_weights_path is not None:
    report = model.load_radimagenet_weights(config.radimagenet_weights_path)
    print(report.summary())
else:
    print("radimagenet_weights_path is None -- backbone remains randomly initialized.")

total_params = sum(p.numel() for p in model.parameters())
print(f"total parameters: {total_params:,}")"""
)
code(
    """dummy_input = torch.randn(2, config.in_channels, INPUT_SIZE, INPUT_SIZE).to(config.device)
model.eval()
with torch.no_grad():
    dummy_output = model(dummy_input)
assert dummy_output.shape == (2,)
print(f"input shape : {tuple(dummy_input.shape)}  output shape: {tuple(dummy_output.shape)}  shapes OK.")"""
)

# Training
md(
    """## Training

Ohashi replication configuration (`configs/training.yaml`): **Adam**,
lr=1e-3, **MSE** loss, batch size 64, 30 epochs. No scheduler, warmup,
weight decay, augmentation, or mixed precision -- all deliberately absent
so this run stays close to the paper's stated configuration. Set
`RUN_FULL_TRAINING = True` to execute the full `config.epochs`-epoch run;
left `False` this cell only verifies the pipeline runs (loss finite,
weights change) without committing to the full run time."""
)
code(
    """optimizer = build_optimizer(model, config)
criterion = build_loss(config)
print(optimizer)
print(criterion)"""
)
code(
    """RUN_FULL_TRAINING = False  # set True to run all config.epochs epochs

if RUN_FULL_TRAINING:
    history = train(model, train_loader, val_loader, config)
else:
    history = None
    print("RUN_FULL_TRAINING is False -- skipping the full training loop.")
    print("Set RUN_FULL_TRAINING = True above and re-run this cell for a real training run.")"""
)
code(
    """if history is not None:
    plt.figure(figsize=(6, 4))
    plt.plot(history.train_loss, label="train")
    plt.plot(history.val_loss, label="val")
    plt.axvline(history.best_epoch, color="gray", linestyle="--", label="best epoch")
    plt.xlabel("epoch")
    plt.ylabel("MSE loss (normalized [0,1] target space)")
    plt.legend()
    plt.title("Training/validation loss")
    plt.show()
else:
    print("No training history -- RUN_FULL_TRAINING was False in this run.")"""
)

# Checkpoint
md(
    """## Checkpoint

The best-validation-loss checkpoint is written to
`experiments/001_resnet50_baseline/checkpoint/best.pt` by
`ct_iqa.training.trainer.train` (via `ct_iqa.training.checkpointing`).
Experiment-generated checkpoints live under `experiments/`, never under
`weights/` -- `weights/pretrained/` is reserved for externally-sourced
pretrained weights only."""
)
code(
    """config.save(Path(config.experiment_dir) / "config.json")
print(f"saved experiment configuration to {Path(config.experiment_dir) / 'config.json'}")
print(f"checkpoint directory: {config.checkpoint_dir}")
print(f"checkpoint present  : {(Path(config.checkpoint_dir) / 'best.pt').exists()}")"""
)

# Notes
md(
    """## Notes

- **RadImageNet weights**: see `weights/pretrained/radimagenet/resnet50/README.md`
  for current provenance/verification status before trusting any backbone
  initialization claim.
- **`RUN_FULL_TRAINING`**: left `False` by default in this generator; a real
  30-epoch run must be started deliberately.
- Continue in `notebooks/04_evaluation/01_test_set_evaluation.ipynb`, which
  loads this run's checkpoint independently rather than relying on this
  notebook's in-memory state."""
)

nb["cells"] = cells
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10"},
}

out_path = Path("notebooks/03_training/01_resnet50_baseline.ipynb")
out_path.parent.mkdir(parents=True, exist_ok=True)
with out_path.open("w", encoding="utf-8") as f:
    nbf.write(nb, f)
print(f"wrote {out_path}")
